origin_prefixes:
    isr: 'git@github.com:intelligent-soft-robots/'
    mim: 'git@github.com:machines-in-motion/'
    odri: 'git@github.com:open-dynamic-robot-initiative/'
    robotics: 'git@git-amd.tuebingen.mpg.de:robotics/'
    https-pybind: 'https://github.com/pybind/'
