origin_prefixes:
    isr: 'git@github.com:intelligent-soft-robots/'
    mim: 'git@github.com:machines-in-motion/'
    odri: 'git@github.com:open-dynamic-robot-initiative/'
    mpi-is: 'git@github.com:MPI-IS/'
    robotics: 'git@gitlab.is.tuebingen.mpg.de:robotics/'
    https-pybind: 'https://github.com/pybind/'
    https-ament: 'https://github.com/ament/'
    https-ros2: 'https://github.com/ros2/'